import type { Metadata } from "next";
import { ThemeProvider } from "@/components/editor/theme-provider"
import { ReactNode } from "react";


export const metadata: Metadata = {
  title: "G6-Editor",
  description: "Generated by G6-team",
};
export default function Layout({children}:{children:ReactNode}) {
  return (
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
          {children}
        </ThemeProvider>
  );
}
